/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import javax.mail.*;
import javax.mail.internet.*;
import java.io.UnsupportedEncodingException;
import java.util.*;

public class App {
	public static void main(String[] args) {
		Properties props = new Properties();
		Session session = Session.getInstance(props);
		MimeMessage msg = new MimeMessage(session);
		Transport t = null;
		try {
			Address bill = new InternetAddress("god@microsoft.com",
					"Harry Yen");
			Address elliotte = new InternetAddress("harry5232@gmail.com");
			msg.setText("Nice to meet you!");
			msg.setFrom(bill);
			msg.setRecipient(Message.RecipientType.TO, elliotte);
			msg.setSubject("HELLO !!");
			t = session.getTransport("smtps");
			t.connect("smtp.gmail.com", "wayne19911126@gmail.com", "morepowermoreduty");
			t.sendMessage(msg, msg.getAllRecipients());
		} catch (MessagingException | UnsupportedEncodingException ex) {
			ex.printStackTrace();
		} finally { // Transport does not implement AutoCloseable :-(
			if (t != null) {
				try {
					t.close();
				} catch (MessagingException ex) {
				}
			}
		}
	}
}
