/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.io.File;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.Properties;

import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.Address;
import javax.mail.BodyPart;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;


//±H°e¤å¦r+¹Ï¤ù email
public class EmailSender {
	public static void main(String[] args) {
		File d = new File("customers");
		File[] fs = d.listFiles();
		for (int i = 0; i < d.listFiles().length; i++) {
			String fName = fs[i].getName();
			
			read_mail(fName);
			// System.out.println(fs[i].getName());
		}
	}

	public static void read_mail(String fName) {
		try {
			Workbook workbook = Workbook.getWorkbook(new File("customers\\"+fName));
			Sheet sheet = (Sheet) workbook.getSheet(0);
			Cell[] p = ((jxl.Sheet) sheet).getColumn(0);

			for (int i = 1; i < p.length; i++) {
				String mail = p[i].getContents();
				
				sendMail(mail);
				// System.out.println(p[i].getContents());
			}
			// System.out.println(sheet.getCell(0, 1).getContents());
			workbook.close();

		} catch (BiffException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public static void sendMail(String address) {
		
		Properties props = new Properties();
		Session session = Session.getInstance(props);
		MimeMessage msg = new MimeMessage(session);
		Transport t = null;
		try {
			Address harry = new InternetAddress("wayne19911126@gmail.com",
					"Harry Yen");
			Address elliotte = new InternetAddress(address);
			// msg.setText("Nice to meet you!");
			msg.setFrom(harry);
			msg.setRecipient(Message.RecipientType.TO, elliotte);
			msg.setSubject("HELLO !!");

			// This mail has 2 part, the BODY and the embedded image
			MimeMultipart multipart = new MimeMultipart("related");

			// first part (the html)
			BodyPart messageBodyPart = new MimeBodyPart();
			String htmlText = "<H1>Greetings customer</H1>"
					+ "<p>I am pleased to meet you. This is <font color=\"#FF0000\">Harry Yen from Unison Tek.</font></p>"
					+ "<p>We found your e-mail address on your company website, and I am seeking an opportunity to provide you our good pricing for customized machining service. Our sales team plans to visit this year and would like to know if there is a chance to visit you !!</p>"

					+ "<p>Are you looking for an alternative vendor for <font color=\"#FF0000\">custom parts?</font></p>"
					+ "<p>Learning more about your requirements in your parts will help us know how to bring <font color=\"#FF0000\">savings & advantages</font> when working with you.</p>"
					+ "<p>We believe we can provide full support on your business <font color=\"#FF0000\">cutting down some costs.</font></p>"
					+ "<p>We have been expanding our service capacity by the years. We even plan to have some one locally at your premises to fully understand your requirements and to smooth things out in business.</p>"
					+ "<p>We have been working on laser micro machining, industrial microscopy & fluid control parts for nearly two decades</p>"
					+ "<p>I know you may already have a supplier for these parts at the moment.</p>"
					+ "<p>Just let you know we are also happy to <font color=\"#FF0000\">provide a budgetary quote</font> to support your purchasing affairs. </p>"
					+ "<p>We really look forward working with you. </p>"
					+ "<p>Is there a time for a conference call by the end of this week?</p>"
					+ "<p>With Best Regards</p>"

					+ "<h3><font color=\"#FF0000\">UNISON TEK CO LTD - Quality CNC Machining Services   Expert of Custom Metal Parts</font></h3>"
					+ "<p>Sales Manager Harry Yen</p>"
					+ "<p>No. 83 Singhua St. Sanchong District</p>"
					+ "<p>New Taipei City 24161 Taiwan R. O. C.</p>"
					+ "<p>Tel 886-2-8981-2067 x 100</p>"
					+ "<p>Fax 886-2-8981-2025</p>"
					+ "<p><b>My e-mail hyen@unisontek.com.tw</b></p>"
					+ "<p><b>Company website http://www.unisontekco.com</b></p>"

					+ "<img src=\"cid:image\">" + "<img src=\"cid:image2\">"
					+ "<img src=\"cid:image3\">" + "<img src=\"cid:image4\">"
					+ "<img src=\"cid:image5\">" + "<img src=\"cid:image6\">";
			messageBodyPart.setContent(htmlText, "text/html");
			// add it
			multipart.addBodyPart(messageBodyPart);

			// second part (the image)
			messageBodyPart = new MimeBodyPart();
			DataSource fds = new FileDataSource(
					"C:\\Users\\Harry\\git\\paper_JavaMail\\t\\picture\\9.jpg");

			messageBodyPart.setDataHandler(new DataHandler(fds));
			messageBodyPart.setHeader("Content-ID", "<image>");

			// add image to the multipart
			multipart.addBodyPart(messageBodyPart);

			// second part (the image)
			messageBodyPart = new MimeBodyPart();
			DataSource fds2 = new FileDataSource(
					"C:\\Users\\Harry\\git\\paper_JavaMail\\t\\picture\\10.jpg");

			messageBodyPart.setDataHandler(new DataHandler(fds2));
			messageBodyPart.setHeader("Content-ID", "<image2>");

			// add image to the multipart
			multipart.addBodyPart(messageBodyPart);

			// second part (the image)
			messageBodyPart = new MimeBodyPart();
			DataSource fds3 = new FileDataSource(
					"C:\\Users\\Harry\\git\\paper_JavaMail\\t\\picture\\11.jpg");

			messageBodyPart.setDataHandler(new DataHandler(fds3));
			messageBodyPart.setHeader("Content-ID", "<image3>");

			// add image to the multipart
			multipart.addBodyPart(messageBodyPart);

			// second part (the image)
			messageBodyPart = new MimeBodyPart();
			DataSource fds4 = new FileDataSource(
					"C:\\Users\\Harry\\git\\paper_JavaMail\\t\\picture\\4.jpg");

			messageBodyPart.setDataHandler(new DataHandler(fds4));
			messageBodyPart.setHeader("Content-ID", "<image4>");

			// add image to the multipart
			multipart.addBodyPart(messageBodyPart);

			// second part (the image)
			messageBodyPart = new MimeBodyPart();
			DataSource fds5 = new FileDataSource(
					"C:\\Users\\Harry\\git\\paper_JavaMail\\t\\picture\\5.jpg");

			messageBodyPart.setDataHandler(new DataHandler(fds5));
			messageBodyPart.setHeader("Content-ID", "<image5>");

			// add image to the multipart
			multipart.addBodyPart(messageBodyPart);

			// second part (the image)
			messageBodyPart = new MimeBodyPart();
			DataSource fds6 = new FileDataSource(
					"C:\\Users\\Harry\\git\\paper_JavaMail\\t\\picture\\6.jpg");

			messageBodyPart.setDataHandler(new DataHandler(fds6));
			messageBodyPart.setHeader("Content-ID", "<image6>");

			// add image to the multipart
			multipart.addBodyPart(messageBodyPart);
			// put everything together
			msg.setContent(multipart);

			t = session.getTransport("smtps");
			t.connect("smtp.gmail.com", "wayne19911126@gmail.com",
					"morepowermoreduty");
			t.sendMessage(msg, msg.getAllRecipients());
		} catch (MessagingException | UnsupportedEncodingException ex) {
			ex.printStackTrace();
		} finally { // Transport does not implement AutoCloseable :-(
			if (t != null) {
				try {
					t.close();
				} catch (MessagingException ex) {
				}
			}
		}

	}

}
